GET http://localhost:8080/api/buscar/usuarios/test5
###
GET https://restserver-nodeudemy.herokuapp.com/api/buscar/categorias/61abf1524ce8b7080d252c4b
###
GET http://localhost:8080/api/buscar/productos/galletas
###