GET http://localhost:8080/api/usuarios

###
GET http://localhost:8080/api/usuarios

###
GET https://restserver-nodeudemy.herokuapp.com/api/usuarios?nombre=RobertoQuintero&edad=35

###

POST   http://localhost:8080/api/usuarios
Content-Type: application/json

{
  "nombre":"Test 21",
  "correo":"test21@test.com",
  "password":"123456",
  "rol":"USER_ROLE"

}
###

PUT  http://localhost:8080/api/usuarios/619fd9534d51dbfc8205d199
Content-Type: application/json

{
  "nombre":"Juan Carlos",
  "google":true,
  "correo":"test0@test.com",
  "password":"123456",
  "rol":"SUPER_ROLE"
}

###

PUT   http://localhost:8080/api/usuarios/10
Content-Type: application/json

{
  "nombre":"Roberto",
  "edad":32
}
###
DELETE http://localhost:8080/api/usuarios/619feee436a2dea09340c94b
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTlmZWU0ZjM2YTJkZWEwOTM0MGM5MDMiLCJpYXQiOjE2MzgwNDE5NTYsImV4cCI6MTYzODA1NjM1Nn0.V6wiGSjzaRH9tqsGwnFDP1KYKk24ma9u8MT1lhnGd5I

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "correo":"test1@test.com",
 "password":"123456"
}
###

POST http://localhost:8080/api/auth/google
Content-Type: application/json

{
  "id_token":"test1@test.com"
}